#!/usr/bin/env ruby

# enable local usage from cloned repo
root = File.expand_path('../..', __FILE__)
$LOAD_PATH << "#{root}/lib" if File.exist?("#{root}/Gemfile")

require 'i18n_flow'
require 'i18n_flow/cli'

I18nFlow.config.auto_configure!
I18nFlow::CLI.new(ARGV).run
